### PR TITLE
fix(tb-node): Increase timeout for readiness probe.

### PR DESCRIPTION
**Pull request by dmitry-midokura**
JIRA: https://midokura.atlassian.net/browse/EVP-2756

The issue in my local deployment:

```
NAME                                              READY   STATUS    RESTARTS        AGE
evp-api-84c65c4c5-9rfn4                           1/1     Running   1 (2m20s ago)   5m54s
evp-env-cert-manager-5d5949cf8b-zzxpm             1/1     Running   0               27m
evp-env-cert-manager-cainjector-656b55895-qt7ws   1/1     Running   0               27m
evp-env-cert-manager-webhook-c5ff45ff6-m22sb      1/1     Running   0               27m
evp-env-controller-5965f74989-lgsjc               1/1     Running   0               27m
evp-init-tb-db-3-dfn8g                            1/1     Running   0               4m49s
evp-jsexecutor-db6b957bc-bncsw                    1/1     Running   0               24m
evp-kafka-0                                       1/1     Running   0               24m
evp-mqtt-transport-0                              1/1     Running   0               24m
evp-node-0                                        0/1     Running   1 (2m4s ago)    24m
evp-pgpool-74fd9b7ff7-8n6l8                       1/1     Running   0               24m
evp-postgresql-0                                  1/1     Running   0               24m
evp-redis-master-649dd8b5d8-2lfxv                 1/1     Running   0               24m
evp-tb-pgpool-ffd7f88f7-h9th9                     1/1     Running   0               24m
evp-tb-postgresql-0                               1/1     Running   0               24m
evp-web-ui-68f764bbf-ndcvs                        1/1     Running   0               24m
evp-zookeeper-0                                   1/1     Running   0               24m
metallb-controller-7567fb574-wg2hp                1/1     Running   0               28m
metallb-speaker-58wd2                             1/1     Running   1 (2m37s ago)   28m
storage-azurite-deployment-85776bbdc9-cm45v       1/1     Running   0               26m
```

### CODE REVIEW

**Comment by maht** [comment]
The Jira ticket do not explain much about the reasons for doing this (error logs, etc). Also, it says `Make it configurable first` which this PR does not address (maybe in another PR?).

**Comment by dmitry-midokura** [comment]
> The Jira ticket do not explain much about the reasons for doing this (error logs, etc). Also, it says `Make it configurable first` which this PR does not address (maybe in another PR?).

Yes, we should definitely make these parameters configurable. The current change is step forward as it should make e2e tests more stable. I won't close JIRA with only this change.

**Comment by maht** [comment]
Please add some error logs, they will be useful to correlate future occurrences of those errors with kind of solution.

**Comment by dmitry-midokura** [comment]
> Please add some error logs, they will be useful to correlate future occurrences of those errors with kind of solution.

I added the 'kubectl get pods' output at the moment when tb-node was restarted on my local deployment. I dont' have logs so far, but describe pod was saying that pod failed liveness check.

**Review by sergioalmendrosdiaz — APPROVED** [review]

**Pull request merged**
